### ISSUE TITLE
Is it possible to start publishing latest releases?

### ISSUE THREAD

**Issue by leo-mendoza-qatalog** [marblekirby/budibase-big-query-plugin#1]
Hello!

I'm very interested in using this plugin, however when I try to install via the add new plugin screen I receive this error:

<img width="977" alt="Screenshot 2022-11-29 at 22 09 09" src="https://user-images.githubusercontent.com/59561721/204659305-3fbc18d4-9424-4078-a54d-4084b8dcd74d.png">

I'm guessing it's because there are no published releases in this repo?

I'm happy to submit a pull request to support this, but I've got no experience with budibase plugins so any guidance would be helpful

**Comment by marblekirby** [comment]
Hi @leo-mendoza-qatalog , I see PR #2 will enable publishing and will allow you to install via github

**Comment by leo-mendoza-qatalog** [comment]
Closing as PR #2 makes this installable 🎉
